# Generated by Django 4.2.5 on 2026-03-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0062_city_hospital_district_hospital'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailssupplies',
            unique_together=set(),
        ),
    ]
